//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogGetAccess
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid GetAccessUserID { get; set; }
        public System.DateTime CD { get; set; }
    }
}
