//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealEstateAgencyEntities : DbContext
    {
        public RealEstateAgencyEntities()
            : base("name=RealEstateAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ads> Ads { get; set; }
        public virtual DbSet<DistrictNames> DistrictNames { get; set; }
        public virtual DbSet<ObjectPhoto> ObjectPhoto { get; set; }
        public virtual DbSet<ObjectProcessingStatus> ObjectProcessingStatus { get; set; }
        public virtual DbSet<ObjectStatus> ObjectStatus { get; set; }
        public virtual DbSet<ObjectTypes> ObjectTypes { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserStatus> UserStatus { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Objects> Objects { get; set; }
        public virtual DbSet<Deals> Deals { get; set; }
        public virtual DbSet<AccountsPhoto> AccountsPhoto { get; set; }
        public virtual DbSet<DealsCounter> DealsCounter { get; set; }
        public virtual DbSet<DealStatus> DealStatus { get; set; }
        public virtual DbSet<ProgrammVersion> ProgrammVersion { get; set; }
        public virtual DbSet<LogAuthtorization> LogAuthtorization { get; set; }
        public virtual DbSet<LogGetAccess> LogGetAccess { get; set; }
    }
}
