//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectProcessingStatus
    {
        public System.Guid ID { get; set; }
        public System.Guid StatusID { get; set; }
        public System.Guid ObjectID { get; set; }
        public string Note { get; set; }
        public System.Guid Author { get; set; }
        public System.DateTime CD { get; set; }
    }
}
