//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        public System.Guid ID { get; set; }
        public string NameObj { get; set; }
        public int CountRoom { get; set; }
        public int Floor { get; set; }
        public double SObject { get; set; }
        public double Coast { get; set; }
        public System.Guid DistrictID { get; set; }
        public string Adress { get; set; }
        public System.Guid Status { get; set; }
        public System.Guid OwnerID { get; set; }
        public System.Guid AgentID { get; set; }
        public System.DateTime CD { get; set; }
        public string Note { get; set; }
        public double SaleProcent { get; set; }
        public double SaleCost { get; set; }
    }
}
