//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public System.Guid ID { get; set; }
        public System.Guid AgentID { get; set; }
        public System.Guid DealID { get; set; }
        public System.Guid UserID { get; set; }
        public string Note { get; set; }
        public double Rating { get; set; }
        public System.DateTime CD { get; set; }
    }
}
